# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Teste
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.8.5
    - name: Install python dependencies
      run: |
        pip install -r requirements.txt
    - name: Install ubuntu dependencies
      run: |
        sudo dpkg --add-architecture i386
        sudo apt-get update
        sudo apt-get install gcc make libxft2:i386 libxext6:i386 \
        libncurses5:i386 libstdc++6:i386 libpng-dev \
        libpng16-16:i386 libpng16-16 python-gobject libnotify-bin 
        
        wget https://ftp.osuosl.org/pub/libpng/src/libpng12/libpng-1.2.59.tar.xz
        tar xvf libpng-1.2.59.tar.xz
        cd libpng-1.2.59/
        ./configure --prefix=/usr/local
        make
        sudo make install
        sudo ldconfig
        
    - name: install modelsim
      run: |
       
